### ISSUE TITLE
The dataset is not exist

### ISSUE THREAD

**Issue by leorusLao** [Okbaydere/CQSS-DTW#1]
Hello, I wanted to reproduce your code, but found that the dataset resource no longer exists.

**Comment by Okbaydere** [comment]
> Hello, I wanted to reproduce your code, but found that the dataset resource no longer exists.

Hello, unfortunately, I obtained the dataset through an article. However, when I click on the link in the article now, I can't access it. I think the author of the article has removed the dataset.

**Comment by leorusLao** [comment]
> > Hello, I wanted to reproduce your code, but found that the dataset resource no longer exists.
> 
> Hello, unfortunately, I obtained the dataset through an article. However, when I click on the link in the article now, I can't access it. I think the author of the article has removed the dataset.

Thank you. That's really a shame.

**Comment by Okbaydere** [comment]
> > > Hello, I wanted to reproduce your code, but found that the dataset resource no longer exists.
> > 
> > 
> > Hello, unfortunately, I obtained the dataset through an article. However, when I click on the link in the article now, I can't access it. I think the author of the article has removed the dataset.
> 
> Thank you. That's really a shame.

Hello again. Today, while going through my old computer, I found the database. If you're still interested in the code, I can upload it to Google Drive and send it to you^^
